_wandb:
    value:
        cli_version: 0.19.10
        m:
            - "1": valid/averagepopularity@10
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": valid_step
              "6": []
              "7": []
            - "1": valid/recall@10
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": valid/hit@10
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": valid/ndcg@10
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": valid/precision@10
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": valid/giniindex@10
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": valid/tailpercentage@10
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/epoch
              "5": 10
              "6":
                - 1
                - 3
              "7": []
            - "1": train_step
              "6": []
              "7": []
            - "1": train/train_loss
              "5": 10
              "6":
                - 1
                - 3
              "7": []
            - "1": valid/itemcoverage@10
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": valid/shannonentropy@10
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.10.17
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 30
                - 36
                - 53
                - 55
            "2":
                - 1
                - 2
                - 3
                - 5
                - 30
                - 36
                - 53
                - 55
            "3":
                - 7
                - 16
                - 23
                - 55
                - 62
            "4": 3.10.17
            "5": 0.19.10
            "8":
                - 1
                - 5
            "12": 0.19.10
            "13": darwin-arm64
dataset:
    value: lastfm-nl
external_config_dict:
    value:
        ITEM_ID_FIELD: artist_id
        LABEL_FIELD: label
        USER_ID_FIELD: user_id
        benchmark_filename:
            - train
            - valid
            - test
        checkpoint_dir: checkpoint_saved/lastfm-nl/
        data_path: datasets/
        dataloaders_save_path: null
        dataset: lastfm-nl
        dataset_save_path: null
        date: null
        embedding_size: 64
        encoding: utf-8
        epochs: 100
        eval_args:
            mode:
                test: full
                valid: full
        eval_batch_size: 4096
        eval_step: 1
        field_separator: "\t"
        gpu_id: "0"
        learner: adam
        learning_rate: 0.0005
        load_col:
            inter:
                - user_id
                - artist_id
                - label
        log_root: outputs/logs/
        log_wandb: true
        metric_decimal_place: 4
        metrics:
            - Precision
            - Recall
            - Hit
            - NDCG
            - ItemCoverage
            - AveragePopularity
            - ShannonEntropy
            - GiniIndex
            - TailPercentage
        model: BPR
        output_path: outputs/lastfm-nl/
        reg_weight: 0.0003
        repeatable: true
        reproducibility: true
        save_dataloaders: true
        save_dataset: true
        seed: 42
        seq_separator: ' '
        show_progress: false
        shuffle: true
        skip_test: false
        state: INFO
        stopping_step: 10
        tail_ratio: 0.2
        timestamp: null
        topk: 10
        train_batch_size: 1024
        train_neg_sample_args:
            alpha: 1
            candidate_num: 0
            distribution: uniform
            dynamic: false
            sample_num: 1
        valid_metric: NDCG@10
        valid_metric_bigger: true
        wandb_path: outputs/
        wandb_project: jiaqing61-tud
        wandb_run_id: null
        wandb_run_name: null
        workers: 2
file_config_dict:
    value:
        ITEM_ID_FIELD: artist_id
        LABEL_FIELD: label
        USER_ID_FIELD: user_id
        benchmark_filename:
            - train
            - valid
            - test
        checkpoint_dir: checkpoint_saved/lastfm-nl/
        data_path: datasets/
        dataloaders_save_path: null
        dataset: lastfm-nl
        dataset_save_path: null
        date: null
        embedding_size: 64
        encoding: utf-8
        epochs: 100
        eval_args:
            mode:
                test: full
                valid: full
        eval_batch_size: 4096
        eval_step: 1
        field_separator: "\t"
        gpu_id: "0"
        learner: adam
        learning_rate: 0.0005
        load_col:
            inter:
                - user_id
                - artist_id
                - label
        log_root: outputs/logs/
        log_wandb: true
        metric_decimal_place: 4
        metrics:
            - Precision
            - Recall
            - Hit
            - NDCG
            - ItemCoverage
            - AveragePopularity
            - ShannonEntropy
            - GiniIndex
            - TailPercentage
        model: BPR
        output_path: outputs/lastfm-nl/
        reg_weight: 0.0003
        repeatable: true
        reproducibility: true
        save_dataloaders: true
        save_dataset: true
        seed: 42
        seq_separator: ' '
        show_progress: false
        shuffle: true
        skip_test: false
        state: INFO
        stopping_step: 10
        tail_ratio: 0.2
        timestamp: null
        topk: 10
        train_batch_size: 1024
        train_neg_sample_args:
            alpha: 1
            candidate_num: 0
            distribution: uniform
            dynamic: false
            sample_num: 1
        valid_metric: NDCG@10
        valid_metric_bigger: true
        wandb_path: outputs/
        wandb_project: jiaqing61-tud
        wandb_run_id: null
        wandb_run_name: null
        workers: 2
final_config_dict:
    value:
        ENTITY_ID_FIELD: entity_id
        HEAD_ENTITY_ID_FIELD: head_id
        ITEM_ID_FIELD: artist_id
        ITEM_LIST_LENGTH_FIELD: item_length
        LABEL_FIELD: label
        LIST_SUFFIX: _list
        MAX_ITEM_LIST_LENGTH: 50
        MODEL_INPUT_TYPE: PAIRWISE
        MODEL_TYPE: GENERAL
        NEG_PREFIX: neg_
        POSITION_FIELD: position_id
        RATING_FIELD: rating
        RELATION_ID_FIELD: relation_id
        TAIL_ENTITY_ID_FIELD: tail_id
        TIME_FIELD: timestamp
        USER_ID_FIELD: user_id
        additional_feat_suffix: null
        alias_of_entity_id: null
        alias_of_item_id: null
        alias_of_relation_id: null
        alias_of_user_id: null
        benchmark_filename:
            - train
            - valid
            - test
        checkpoint_dir: checkpoint_saved/lastfm-nl/
        clip_grad_norm: null
        data_path: datasets/lastfm-nl
        dataloaders_save_path: null
        dataset: lastfm-nl
        dataset_save_path: null
        date: null
        device: cpu
        discretization: null
        embedding_size: 64
        enable_amp: false
        enable_scaler: false
        encoding: utf-8
        entity_kg_num_interval: '[0,inf)'
        epochs: 100
        eval_args:
            group_by: user
            mode:
                test: full
                valid: full
            order: RO
            split:
                RS:
                    - 0.8
                    - 0.1
                    - 0.1
        eval_batch_size: 4096
        eval_step: 1
        eval_type: RANKING
        field_separator: "\t"
        filter_inter_by_user_or_item: true
        gpu_id: "0"
        item_inter_num_interval: '[0,inf)'
        kg_reverse_r: false
        learner: adam
        learning_rate: 0.0005
        load_col:
            inter:
                - user_id
                - artist_id
                - label
        local_rank: 0
        log_root: outputs/logs/
        log_wandb: true
        loss_decimal_place: 4
        metric_decimal_place: 4
        metrics:
            - Precision
            - Recall
            - Hit
            - NDCG
            - ItemCoverage
            - AveragePopularity
            - ShannonEntropy
            - GiniIndex
            - TailPercentage
        model: BPR
        normalize_all: null
        normalize_field: null
        numerical_features: []
        output_path: outputs/lastfm-nl/
        preload_weight: null
        reg_weight: 0.0003
        relation_kg_num_interval: '[0,inf)'
        repeatable: true
        reproducibility: true
        require_pow: false
        rm_dup_inter: null
        save_dataloaders: true
        save_dataset: true
        seed: 42
        seq_len: null
        seq_separator: ' '
        show_progress: false
        shuffle: true
        single_spec: true
        skip_test: false
        state: INFO
        stopping_step: 10
        tail_ratio: 0.2
        test_neg_sample_args:
            distribution: uniform
            sample_num: none
        threshold: null
        timestamp: null
        topk:
            - 10
        train_batch_size: 1024
        train_neg_sample_args:
            alpha: 1
            candidate_num: 0
            distribution: uniform
            dynamic: false
            sample_num: 1
        transform: null
        unload_col: null
        unused_col: null
        use_gpu: true
        user_inter_num_interval: '[0,inf)'
        val_interval: null
        valid_metric: NDCG@10
        valid_metric_bigger: true
        valid_neg_sample_args:
            distribution: uniform
            sample_num: none
        wandb_path: outputs/
        wandb_project: jiaqing61-tud
        wandb_run_id: null
        wandb_run_name: null
        weight_decay: 0
        worker: 0
        workers: 2
internal_config_dict:
    value:
        ENTITY_ID_FIELD: entity_id
        HEAD_ENTITY_ID_FIELD: head_id
        ITEM_ID_FIELD: item_id
        ITEM_LIST_LENGTH_FIELD: item_length
        LABEL_FIELD: label
        LIST_SUFFIX: _list
        MAX_ITEM_LIST_LENGTH: 50
        MODEL_TYPE: GENERAL
        NEG_PREFIX: neg_
        POSITION_FIELD: position_id
        RATING_FIELD: rating
        RELATION_ID_FIELD: relation_id
        TAIL_ENTITY_ID_FIELD: tail_id
        TIME_FIELD: timestamp
        USER_ID_FIELD: user_id
        additional_feat_suffix: null
        alias_of_entity_id: null
        alias_of_item_id: null
        alias_of_relation_id: null
        alias_of_user_id: null
        benchmark_filename: null
        checkpoint_dir: saved
        clip_grad_norm: null
        data_path: dataset/
        dataloaders_save_path: null
        dataset_save_path: null
        discretization: null
        embedding_size: 64
        enable_amp: false
        enable_scaler: false
        entity_kg_num_interval: '[0,inf)'
        epochs: 300
        eval_args:
            group_by: user
            mode: full
            order: RO
            split:
                RS:
                    - 0.8
                    - 0.1
                    - 0.1
        eval_batch_size: 4096
        eval_step: 1
        field_separator: "\t"
        filter_inter_by_user_or_item: true
        gpu_id: "0"
        item_inter_num_interval: '[0,inf)'
        kg_reverse_r: false
        learner: adam
        learning_rate: 0.001
        load_col:
            inter:
                - user_id
                - item_id
        log_wandb: false
        loss_decimal_place: 4
        metric_decimal_place: 4
        metrics:
            - Recall
            - MRR
            - NDCG
            - Hit
            - Precision
        normalize_all: null
        normalize_field: null
        numerical_features: []
        preload_weight: null
        relation_kg_num_interval: '[0,inf)'
        repeatable: false
        reproducibility: true
        require_pow: false
        rm_dup_inter: null
        save_dataloaders: false
        save_dataset: false
        seed: 2020
        seq_len: null
        seq_separator: ' '
        show_progress: true
        shuffle: true
        state: INFO
        stopping_step: 10
        threshold: null
        topk:
            - 10
        train_batch_size: 2048
        train_neg_sample_args:
            alpha: 1
            candidate_num: 0
            distribution: uniform
            dynamic: false
            sample_num: 1
        transform: null
        unload_col: null
        unused_col: null
        use_gpu: true
        user_inter_num_interval: '[0,inf)'
        val_interval: null
        valid_metric: MRR@10
        valid_metric_bigger: true
        wandb_project: recbole
        weight_decay: 0
        worker: 0
model:
    value: BPR
model_class:
    value: recbole.model.general_recommender.bpr.BPR
parameters:
    value:
        Dataset:
            - field_separator
            - seq_separator
            - USER_ID_FIELD
            - ITEM_ID_FIELD
            - RATING_FIELD
            - TIME_FIELD
            - seq_len
            - LABEL_FIELD
            - threshold
            - NEG_PREFIX
            - ITEM_LIST_LENGTH_FIELD
            - LIST_SUFFIX
            - MAX_ITEM_LIST_LENGTH
            - POSITION_FIELD
            - HEAD_ENTITY_ID_FIELD
            - TAIL_ENTITY_ID_FIELD
            - RELATION_ID_FIELD
            - ENTITY_ID_FIELD
            - load_col
            - unload_col
            - unused_col
            - additional_feat_suffix
            - rm_dup_inter
            - val_interval
            - filter_inter_by_user_or_item
            - user_inter_num_interval
            - item_inter_num_interval
            - alias_of_user_id
            - alias_of_item_id
            - alias_of_entity_id
            - alias_of_relation_id
            - preload_weight
            - normalize_field
            - normalize_all
            - benchmark_filename
        Evaluation:
            - eval_args
            - repeatable
            - metrics
            - topk
            - valid_metric
            - valid_metric_bigger
            - eval_batch_size
            - metric_decimal_place
        General:
            - gpu_id
            - use_gpu
            - seed
            - reproducibility
            - state
            - data_path
            - checkpoint_dir
            - show_progress
            - config_file
            - save_dataset
            - dataset_save_path
            - save_dataloaders
            - dataloaders_save_path
            - log_wandb
        Training:
            - epochs
            - train_batch_size
            - learner
            - learning_rate
            - train_neg_sample_args
            - eval_step
            - stopping_step
            - clip_grad_norm
            - weight_decay
            - loss_decimal_place
yaml_loader:
    value: yaml.loader.FullLoader
